name: FB Auto Posting Workflow

on:
  schedule:
    - cron: '*/30 * * * *' # මෙයින් සෑම විනාඩි 30කට වරක්ම පසුබිමෙන් ඇප් එක වැඩ කර ලංකාවේ වෙලාව පරීක්ෂා කරයි

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests supabase

      - name: Run Auto Poster Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python cron_script.py
